//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountHistory
    {
        public long acc_his_id { get; set; }
        public Nullable<int> acc_his_status { get; set; }
        public string acc_his_desc { get; set; }
        public Nullable<long> acc_id { get; set; }
        public Nullable<decimal> acc_amount_change { get; set; }
    
        public virtual mAccount mAccount { get; set; }
    }
}
