//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin()
        {
            this.borrow_hd = new HashSet<borrow_hd>();
        }
    
        public string admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_address { get; set; }
        public string admin_description { get; set; }
        public string admin_tell { get; set; }
        public string admin_idcard { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrow_hd> borrow_hd { get; set; }
    }
}
