//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrow_dt
    {
        public string bor_id { get; set; }
        public int roworder { get; set; }
        public string equ_id { get; set; }
        public Nullable<int> bor_amount { get; set; }
        public Nullable<System.DateTime> bor_date { get; set; }
        public Nullable<System.DateTime> bor_wxp { get; set; }
    
        public virtual borrow_hd borrow_hd { get; set; }
        public virtual equipment equipment { get; set; }
    }
}
