//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mMember()
        {
            this.borrow_hd = new HashSet<borrow_hd>();
            this.mAccounts = new HashSet<mAccount>();
        }
    
        public string mem_id { get; set; }
        public string mem_name { get; set; }
        public Nullable<int> mem_address_id { get; set; }
        public string mem_email { get; set; }
        public string mem_phone { get; set; }
        public string mem_idcard { get; set; }
        public string mem_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrow_hd> borrow_hd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAccount> mAccounts { get; set; }
        public virtual memberType memberType { get; set; }
    }
}
