//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JAOEntities : DbContext
    {
        public JAOEntities()
            : base("name=JAOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountHistory> accountHistories { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<borrow_dt> borrow_dt { get; set; }
        public virtual DbSet<borrow_hd> borrow_hd { get; set; }
        public virtual DbSet<equ_category> equ_category { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<mAccount> mAccounts { get; set; }
        public virtual DbSet<memberType> memberTypes { get; set; }
        public virtual DbSet<mMember> mMembers { get; set; }
    }
}
